config/routes.rb
Servermine::Application.routes.draw do
  devise_for :accounts, :path => 'account'

  root :to => "account/servers#index"

  namespace :account do
    resources :servers do
      resource :server_properties, :controller => 'servers/server_properties'
      resource :ops, :controller => 'servers/ops'
      resource :banned_players, :controller => 'servers/banned_players'
      resource :banned_ips, :controller => 'servers/banned_ips'
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :confirmable, :lockable

  # associations
  has_many :servers

  # whitelisted attributes for mass-assignment
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/ip.rb
class Ip < ActiveRecord::Base

  validates :address, :presence => true

end

app/models/player.rb
class Player < ActiveRecord::Base

  # validations
  validates_presence_of :username
  validates_uniqueness_of :username, :case_sensitive => false

end

app/models/server.rb
class Server < ActiveRecord::Base
  # associations
  belongs_to :account
  has_one    :server_properties
  has_and_belongs_to_many :ops, :class_name => 'Player', :join_table => 'ops_servers'
  has_and_belongs_to_many :banned_players, :class_name => 'Player', :join_table => 'banned_players_servers'
  has_and_belongs_to_many :banned_ips, :class_name => 'Ip', :join_table => 'banned_ips_servers'

  accepts_nested_attributes_for :ops, :allow_destroy => true
  accepts_nested_attributes_for :banned_players, :allow_destroy => true
  accepts_nested_attributes_for :banned_ips, :allow_destroy => true

  # validations
  validates_presence_of :account

  # callbacks
  after_create :create_server_properties

  def create_ops_file
    file_path = Rails.root.join('tmp', "opts-#{Time.now.to_f}")
    File.open(file_path, 'w') do |file|
      ops.each do |player|
        file.write "#{player.username}\r\n"
      end
    end
    file_path
  end

  def create_banned_players_file
    file_path = Rails.root.join('tmp', "banned_players-#{Time.now.to_f}")
    File.open(file_path, 'w') do |file|
      banned_players.each do |player|
        file.write "#{player.username}\r\n"
      end
    end
    file_path
  end

  def create_banned_ips_file
    file_path = Rails.root.join('tmp', "banned_ips-#{Time.now.to_f}")
    File.open(file_path, 'w') do |file|
      banned_ips.each do |player|
        file.write "#{player.address}\r\n"
      end
    end
    file_path
  end
end

app/models/server_properties.rb
class ServerProperties < ActiveRecord::Base
  belongs_to :server

  def create_file
    file_path = Rails.root.join('tmp', "#{self.class.name}-#{Time.now.to_f}")
    File.open(file_path, 'w') do |file|
      santised_attributes.each do |key, value|
        file.write "#{key.dasherize}=#{value}\r\n"
      end
    end
    file_path
  end

  private
  def santised_attributes
    attributes_to_write = self.attributes
    attributes_to_write.delete('server_id')
    attributes_to_write.delete('created_at')
    attributes_to_write.delete('updated_at')
    attributes_to_write
  end

end

app/controllers/account/servers/banned_ips_controller.rb
class Account::Servers::BannedIpsController < ApplicationController
  layout 'server'
  before_filter :find_server

  def show
    redirect_to :action => :edit
  end

  def edit
    @banned_ips = @server.banned_ips
  end

  def update
    if @server.update_attributes(params[:server])
      redirect_to [:account, @server]
    else
      render :action => :edit
    end
  end

  private
  def find_server
    @server = current_account.servers.find(params[:server_id])
  end
end

app/controllers/account/servers/banned_players_controller.rb
class Account::Servers::BannedPlayersController < ApplicationController
  layout 'server'
  before_filter :find_server

  def show
    redirect_to :action => :edit
  end

  def edit
    @banned_players = @server.banned_players
  end

  def update
    if @server.update_attributes(params[:server])
      redirect_to [:account, @server]
    else
      render :action => :edit
    end
  end

  private
  def find_server
    @server = current_account.servers.find(params[:server_id])
  end
end

app/controllers/account/servers/ops_controller.rb
class Account::Servers::OpsController < ApplicationController
  layout 'server'
  before_filter :find_server

  def show
    redirect_to :action => :edit
  end

  def edit
    @ops = @server.ops
  end

  def update
    if @server.update_attributes(params[:server])
      redirect_to [:account, @server]
    else
      render :action => :edit
    end
  end

  private
  def find_server
    @server = current_account.servers.find(params[:server_id])
  end
end

app/controllers/account/servers/server_properties_controller.rb
class Account::Servers::ServerPropertiesController < ApplicationController
  before_filter :find_server

  def show
    redirect_to :action => :edit
  end

  def edit
    @server_properties = @server.server_properties
  end

  def update
    @server_properties = @server.server_properties
    if @server_properties.update_attributes(params[:server_properties])
      redirect_to [:account, @server]
    else
      render :action => :edit
    end
  end

  private
  def find_server
    @server = current_account.servers.find(params[:server_id])
  end
end

app/controllers/account/servers_controller.rb
class Account::ServersController < ApplicationController

  def index
    @servers = current_account.servers
  end

  def show
    @server = current_account.servers.find(params[:id])
    render :show, :layout => 'server'
  end

  def new
    @server = current_account.servers.build
  end

  def create
    @server = current_account.servers.build(params[:server])
    if @server.save
      redirect_to account_servers_path
    else
      render :new
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_account!
end

app/helpers/account/servers/banned_ips_helper.rb
module Account::Servers::BannedIpsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def new_child_fields_template(form_builder, association, options = {})
    options[:object] ||= form_builder.object.class.reflect_on_association(association).klass.new
    options[:partial] ||= association.to_s.singularize
    options[:form_builder_local] ||= :form

    content_for :form_templates do
      content_tag(:div, :id => "#{association}_fields_template", :style => "display: none") do
        form_builder.fields_for(association, options[:object], :child_index => "new_#{association}") do |form|
          render options[:partial], options[:form_builder_local] => form
        end
      end
    end
  end

  def add_child_link(name, association)
    link_to(name, "javascript:void(0)", :class => "add_child", :"data-association" => association)
  end

  def remove_child_link(name, f)
    f.hidden_field(:_destroy) + link_to(name, "javascript:void(0)", :class => "remove_child")
  end
end

app/views/layouts/application.html.haml
= render 'shared/html_declaration'
= render 'shared/header'

#content.container_12
  .grid_12
    .display
      = yield
.clear

app/views/layouts/server.html.haml
= render 'shared/html_declaration'
= render 'shared/header'

#content.container_12
  .grid_9
    .display
      = yield
  .grid_3.side_nav
    .ip_address 192.168.255.255
    = link_to 'Server Overview', [:account, @server]
    = link_to 'Cancel Server', '#', :id => 'cancel_server'

    .group
      .title Game Server
      .links
        = link_to 'Server Properties', [:edit, :account, @server, :server_properties]
        = link_to 'Ops', [:edit, :account, @server, :ops]
        = link_to 'Banned Players', [:edit, :account, @server, :banned_players]
        = link_to 'Banned IPs', [:edit, :account, @server, :banned_ips]
        = link_to 'Import a World', '#'
    .group
      .title World Backups
      .links
        = link_to 'Backup Settings', '#'
        = link_to 'Restore a Backup', '#'
        = link_to 'View Backup Files', '#'

    .group
      .title Virtual Machine
      .sub 1024MB | 2 Virtual Cores
      .links
        = link_to 'Performance', '#'
        = link_to 'Upgrade / Downgrade', '#'
.clear

app/views/shared/_header.html.haml
#header_wrapper
  #header.container_12
    .title.grid_4
      %h1
        %a{:href => root_url}
          Server<span>Mine</span>
    .navigation.grid_4.push_4
      %ul
        - if account_signed_in?
          %li= link_to 'Servers', account_servers_path
          %li= link_to 'My Account', edit_account_registration_path
          %li= link_to 'Logout', destroy_account_session_path
        - else
          %li= link_to 'Login', account_session_path
          %li= link_to 'Sign Up', new_account_registration_path
  .clear

%br/

app/views/shared/_html_declaration.haml
!!! 5
%html
  %head
    = stylesheet_link_tag 'reset', '960', 'application'
    = javascript_include_tag 'jquery', 'rails', 'application'
    = csrf_meta_tag
  %body